export const coffeMakerList =[
  {
    title: 'Keurig K-Duo',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    value: 3,
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/61-KUPluVYL._AC_SL1500_.jpg',
  },
  {
    title: 'KRUPS Electric Spice',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    value: 3,
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/71FhMLBP9XL._AC_SL1500_.jpg',
  },
  {
    title: 'Hamilton Beach Flexbrew',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    value: 3,
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/818rz3CIaFL._AC_SL1500_.jpg',
  },
  {
    value: 3,
    title: 'Secura French Press',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/61XRMmXVwQL._AC_SL1500_.jpg',
  },
  {
    value: 3,
    title: 'Cafe Du Chateau French',
    OldPrice: '$149.99',
    SalePrice: ' $100.99',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/81luUhz7ZlL._AC_SL1500_.jpg',
  },
  {
    value: 3,
    title: 'LIVINGbasics Single  ',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/61KBB8K1wDL._AC_SL1000_.jpg',
  },
  {
    title: 'Keurig K-Duo',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    value: 3,
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/61-KUPluVYL._AC_SL1500_.jpg',
  },
  {
    title: 'KRUPS Electric Spice',
    OldPrice: '$149.99',
    SalePrice: '$100.99',
    value: 3,
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/71FhMLBP9XL._AC_SL1500_.jpg',
  },
];

export const reviewsList=  [
  {
    imageUrl:
    'https://www.w3schools.com/w3images/wedding.jpg',
            name: 'Hajar EL Yemlahi',
      value: 4,cols: 2,
      description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.'
      
  },
  {
    imageUrl:
    'https://picsum.photos/200/200' ,  
         name: 'Souraya El bahri',
    value: 3,cols: 2,
    description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique'
  },
  {
   
    imageUrl:
    'https://picsum.photos/200/200',
            name: 'Mohammed oubenma',
      value: 5, cols: 2,
       description:' Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié',    },
  {
    imageUrl:
    'https://picsum.photos/200/200',        value: 4,cols: 2,
      name: 'Naima El kamel',
      description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500'
  },
  {
  
    imageUrl:
    'https://picsum.photos/200/200',        value: 3,cols: 2,
      name: 'Zakaria El yemlahi',
      description:'Plusieurs variations de Lorem Ipsum peuvent être trouvées ici ou là, mais la majeure partie d\'entre elles a été altérée par l\'addition'
  },
  {
  
    imageUrl:
    'https://picsum.photos/200/200',        value: 4, cols: 2,
     name: 'Meriem El bahri ',
      description:'d\'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard. Si vous voulez utiliser un passage du Lorem Ipsum, vous devez être sûr qu\'il n\'y a rien d\'embarrassant'
  },
  {
   
    imageUrl:
    'https://picsum.photos/200/200',        name: 'Oussama el bahri',cols: 2,
      value: 3,
      description:'d\'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard. Si vous voulez utiliser un passage du Lorem Ipsum, vous devez être sûr qu\'il n\'y a rien d\'embarrassant'

  },
  {
   
    imageUrl:
    'https://picsum.photos/200/200',     name: 'wahicha EL bahri', cols: 2,
      value: 5,
      description:'d\'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard. Si vous voulez utiliser un passage du Lorem Ipsum, vous devez être sûr qu\'il n\'y a rien d\'embarrassant'

  },
  
   
    
   
   
  
];

 export const countries=[
  {name: "Albania", label: "AL"},
  {name: "Åland Islands", label: "AX"},
  {name: "Algeria", label: "DZ"},
  {name: "American Samoa", label: "AS"},
  {name: "Andorra", label: "AD"},
  {name: "Angola", label: "AO"},
  {name: "Anguilla", label: "AI"},
  {name: "Antarctica", label: "AQ"},
  {name: "Antigua and Barbuda", label: "AG"},
  {name: "Argentina", label: "AR"},
  {name: "Armenia", label: "AM"},
  {name: "Aruba", label: "AW"},
  {name: "Australia", label: "AU"},
  {name: "Austria", label: "AT"},
  {name: "Azerbaijan", label: "AZ"},
  {name: "Bahamas (the)", label: "BS"},
  {name: "Bahrain", label: "BH"},
  {name: "Bangladesh", label: "BD"},
  {name: "Barbados", label: "BB"},
  {name: "Belarus", label: "BY"},
  {name: "Belgium", label: "BE"},
  {name: "Belize", label: "BZ"},
  {name: "Benin", label: "BJ"},
  {name: "Bermuda", label: "BM"},
  {name: "Bhutan", label: "BT"},
  {name: "Bolivia (Plurinational State of)", label: "BO"},
  {name: "Bonaire, Sint Eustatius and Saba", label: "BQ"},
  {name: "Bosnia and Herzegovina", label: "BA"},
  {name: "Botswana", label: "BW"},
  {name: "Bouvet Island", label: "BV"},
  {name: "Brazil", label: "BR"},
  {name: "British Indian Ocean Territory (the)", label: "IO"},
  {name: "Brunei Darussalam", label: "BN"},
  {name: "Bulgaria", label: "BG"},
  {name: "Burkina Faso", label: "BF"},
  {name: "Burundi", label: "BI"},
  {name: "Cabo Verde", label: "CV"},
  {name: "Cambodia", label: "KH"},
  {name: "Cameroon", label: "CM"},
  {name: "Canada", label: "CA"},
  {name: "Cayman Islands (the)", label: "KY"},
  {name: "Central African Republic (the)", label: "CF"},
  {name: "Chad", label: "TD"},
  {name: "Chile", label: "CL"},
  {name: "China", label: "CN"},
  {name: "Christmas Island", label: "CX"},
  {name: "Cocos (Keeling) Islands (the)", label: "CC"},
  {name: "Colombia", label: "CO"},
  {name: "Comoros (the)", label: "KM"},
  {name: "Congo (the Democratic Republic of the)", label: "CD"},
  {name: "Congo (the)", label: "CG"},
  {name: "Cook Islands (the)", label: "CK"},
  {name: "Costa Rica", label: "CR"},
  {name: "Croatia", label: "HR"},
  {name: "Cuba", label: "CU"},
  {name: "Curaçao", label: "CW"},
  {name: "Cyprus", label: "CY"},
  {name: "Czechia", label: "CZ"},
  {name: "Côte d'Ivoire", label: "CI"},
  {name: "Denmark", label: "DK"},
  {name: "Djibouti", label: "DJ"},
  {name: "Dominica", label: "DM"},
  {name: "Dominican Republic (the)", label: "DO"},
  {name: "Ecuador", label: "EC"},
  {name: "Egypt", label: "EG"},
  {name: "El Salvador", label: "SV"},
  {name: "Equatorial Guinea", label: "GQ"},
  {name: "Eritrea", label: "ER"},
  {name: "Estonia", label: "EE"},
  {name: "Eswatini", label: "SZ"},
  {name: "Ethiopia", label: "ET"},
  {name: "Falkland Islands (the) [Malvinas]", label: "FK"},
  {name: "Faroe Islands (the)", label: "FO"},
  {name: "Fiji", label: "FJ"},
  {name: "Finland", label: "FI"},
  {name: "France", label: "FR"},
  {name: "French Guiana", label: "GF"},
  {name: "French Polynesia", label: "PF"},
  {name: "French Southern Territories (the)", label: "TF"},
  {name: "Gabon", label: "GA"},
  {name: "Gambia (the)", label: "GM"},
  {name: "Georgia", label: "GE"},
  {name: "Germany", label: "DE"},
  {name: "Ghana", label: "GH"},
  {name: "Gibraltar", label: "GI"},
  {name: "Greece", label: "GR"},
  {name: "Greenland", label: "GL"},
  {name: "Grenada", label: "GD"},
  {name: "Guadeloupe", label: "GP"},
  {name: "Guam", label: "GU"},
  {name: "Guatemala", label: "GT"},
  {name: "Guernsey", label: "GG"},
  {name: "Guinea", label: "GN"},
  {name: "Guinea-Bissau", label: "GW"},
  {name: "Guyana", label: "GY"},
  {name: "Haiti", label: "HT"},
  {name: "Heard Island and McDonald Islands", label: "HM"},
  {name: "Holy See (the)", label: "VA"},
  {name: "Honduras", label: "HN"},
  {name: "Hong Kong", label: "HK"},
  {name: "Hungary", label: "HU"},
  {name: "Iceland", label: "IS"},
  {name: "India", label: "IN"},
  {name: "Indonesia", label: "ID"},
  {name: "Iran (Islamic Republic of)", label: "IR"},
  {name: "Iraq", label: "IQ"},
  {name: "Ireland", label: "IE"},
  {name: "Isle of Man", label: "IM"},
  {name: "Israel", label: "IL"},
  {name: "Italy", label: "IT"},
  {name: "Jamaica", label: "JM"},
  {name: "Japan", label: "JP"},
  {name: "Jersey", label: "JE"},
  {name: "Jordan", label: "JO"},
  {name: "Kazakhstan", label: "KZ"},
  {name: "Kenya", label: "KE"},
  {name: "Kiribati", label: "KI"},
  {name: "Korea (the Democratic People's Republic of)", label: "KP"},
  {name: "Korea (the Republic of)", label: "KR"},
  {name: "Kuwait", label: "KW"},
  {name: "Kyrgyzstan", label: "KG"},
  {name: "Lao People's Democratic Republic (the)", label: "LA"},
  {name: "Latvia", label: "LV"},
  {name: "Lebanon", label: "LB"},
  {name: "Lesotho", label: "LS"},
  {name: "Liberia", label: "LR"},
  {name: "Libya", label: "LY"},
  {name: "Liechtenstein", label: "LI"},
  {name: "Lithuania", label: "LT"},
  {name: "Luxembourg", label: "LU"},
  {name: "Macao", label: "MO"},
  {name: "Madagascar", label: "MG"},
  {name: "Malawi", label: "MW"},
  {name: "Malaysia", label: "MY"},
  {name: "Maldives", label: "MV"},
  {name: "Mali", label: "ML"},
  {name: "Malta", label: "MT"},
  {name: "Marshall Islands (the)", label: "MH"},
  {name: "Martinique", label: "MQ"},
  {name: "Mauritania", label: "MR"},
  {name: "Mauritius", label: "MU"},
  {name: "Mayotte", label: "YT"},
  {name: "Mexico", label: "MX"},
  {name: "Micronesia (Federated States of)", label: "FM"},
  {name: "Moldova (the Republic of)", label: "MD"},
  {name: "Monaco", label: "MC"},
  {name: "Mongolia", label: "MN"},
  {name: "Montenegro", label: "ME"},
  {name: "Montserrat", label: "MS"},
  {name: "Morocco", label: "MA"},
  {name: "Mozambique", label: "MZ"},
  {name: "Myanmar", label: "MM"},
  {name: "Namibia", label: "NA"},
  {name: "Nauru", label: "NR"},
  {name: "Nepal", label: "NP"},
  {name: "Netherlands (the)", label: "NL"},
  {name: "New Caledonia", label: "NC"},
  {name: "New Zealand", label: "NZ"},
  {name: "Nicaragua", label: "NI"},
  {name: "Niger (the)", label: "NE"},
  {name: "Nigeria", label: "NG"},
  {name: "Niue", label: "NU"},
  {name: "Norfolk Island", label: "NF"},
  {name: "Northern Mariana Islands (the)", label: "MP"},
  {name: "Norway", label: "NO"},
  {name: "Oman", label: "OM"},
  {name: "Pakistan", label: "PK"},
  {name: "Palau", label: "PW"},
  {name: "Palestine, State of", label: "PS"},
  {name: "Panama", label: "PA"},
  {name: "Papua New Guinea", label: "PG"},
  {name: "Paraguay", label: "PY"},
  {name: "Peru", label: "PE"},
  {name: "Philippines (the)", label: "PH"},
  {name: "Pitcairn", label: "PN"},
  {name: "Poland", label: "PL"},
  {name: "Portugal", label: "PT"},
  {name: "Puerto Rico", label: "PR"},
  {name: "Qatar", label: "QA"},
  {name: "Republic of North Macedonia", label: "MK"},
  {name: "Romania", label: "RO"},
  {name: "Russian Federation (the)", label: "RU"},
  {name: "Rwanda", label: "RW"},
  {name: "Réunion", label: "RE"},
  {name: "Saint Barthélemy", label: "BL"},
  {name: "Saint Helena, Ascension and Tristan da Cunha", label: "SH"},
  {name: "Saint Kitts and Nevis", label: "KN"},
  {name: "Saint Lucia", label: "LC"},
  {name: "Saint Martin (French part)", label: "MF"},
  {name: "Saint Pierre and Miquelon", label: "PM"},
  {name: "Saint Vincent and the Grenadines", label: "VC"},
  {name: "Samoa", label: "WS"},
  {name: "San Marino", label: "SM"},
  {name: "Sao Tome and Principe", label: "ST"},
  {name: "Saudi Arabia", label: "SA"},
  {name: "Senegal", label: "SN"},
  {name: "Serbia", label: "RS"},
  {name: "Seychelles", label: "SC"},
  {name: "Sierra Leone", label: "SL"},
  {name: "Singapore", label: "SG"},
  {name: "Sint Maarten (Dutch part)", label: "SX"},
  {name: "Slovakia", label: "SK"},
  {name: "Slovenia", label: "SI"},
  {name: "Solomon Islands", label: "SB"},
  {name: "Somalia", label: "SO"},
  {name: "South Africa", label: "ZA"},
  {name: "South Georgia and the South Sandwich Islands", label: "GS"},
  {name: "South Sudan", label: "SS"},
  {name: "Spain", label: "ES"},
  {name: "Sri Lanka", label: "LK"},
  {name: "Sudan (the)", label: "SD"},
  {name: "Suriname", label: "SR"},
  {name: "Svalbard and Jan Mayen", label: "SJ"},
  {name: "Sweden", label: "SE"},
  {name: "Switzerland", label: "CH"},
  {name: "Syrian Arab Republic", label: "SY"},
  {name: "Taiwan (Province of China)", label: "TW"},
  {name: "Tajikistan", label: "TJ"},
  {name: "Tanzania, United Republic of", label: "TZ"},
  {name: "Thailand", label: "TH"},
  {name: "Timor-Leste", label: "TL"},
  {name: "Togo", label: "TG"},
  {name: "Tokelau", label: "TK"},
  {name: "Tonga", label: "TO"},
  {name: "Trinidad and Tobago", label: "TT"},
  {name: "Tunisia", label: "TN"},
  {name: "Turkey", label: "TR"},
  {name: "Turkmenistan", label: "TM"},
  {name: "Turks and Caicos Islands (the)", label: "TC"},
  {name: "Tuvalu", label: "TV"},
  {name: "Uganda", label: "UG"},
  {name: "Ukraine", label: "UA"},
  {name: "United Arab Emirates (the)", label: "AE"},
  {name: "United Kingdom of Great Britain and Northern Ireland (the)", label: "GB"},
  {name: "United States Minor Outlying Islands (the)", label: "UM"},
  {name: "United States of America (the)", label: "US"},
  {name: "Uruguay", label: "UY"},
  {name: "Uzbekistan", label: "UZ"},
  {name: "Vanuatu", label: "VU"},
  {name: "Venezuela (Bolivarian Republic of)", label: "VE"},
  {name: "Viet Nam", label: "VN"},
  {name: "Virgin Islands (British)", label: "VG"},
  {name: "Virgin Islands (U.S.)", label: "VI"},
  {name: "Wallis and Futuna", label: "WF"},
  {name: "Western Sahara", label: "EH"},
  {name: "Yemen", label: "YE"},
  {name: "Zambia", label: "ZM"},
  {name: "Zimbabwe", label: "ZW"}
]
